name: CI

on:
  push:
    branches: [ "main", "staging" ]
    force: true
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute PHP code style fixer via Pint
        run: vendor/bin/pint --test

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          PAYSTACK_PUBLIC_KEY: ${{ secrets.PAYSTACK_PUBLIC_KEY }}
          PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
          APILAYER_API_KEY: ${{ secrets.APILAYER_API_KEY }}
        run: vendor/bin/pest --stop-on-defect --exclude-group=external

  app-deploy:

    needs: [ "laravel-tests" ]

    runs-on: ubuntu-latest

    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')

    steps:
      - uses: actions/checkout@v3

      - name: Determine SSH Private Key
        uses: haya14busa/action-cond@v1
        id: sshprivatekey
        with:
          cond: ${{ github.ref == 'refs/heads/main' }}
          if_true: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          if_false: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Determine SSH Host
        uses: haya14busa/action-cond@v1
        id: sshhost
        with:
          cond: ${{ github.ref == 'refs/heads/main' }}
          if_true: ${{ secrets.SSH_PROD_HOST }}
          if_false: ${{ secrets.SSH_HOST }}

      - name: Determine SSH Directory
        uses: haya14busa/action-cond@v1
        id: sshdirectory
        with:
          cond: ${{ github.ref == 'refs/heads/main' }}
          if_true: ${{ secrets.SSH_PROD_DIRECTORY }}
          if_false: ${{ secrets.SSH_DIRECTORY }}

      - name: Determine SSH User
        uses: haya14busa/action-cond@v1
        id: sshuser
        with:
          cond: ${{ github.ref == 'refs/heads/main' }}
          if_true: ${{ secrets.SSH_PROD_USER }}
          if_false: ${{ secrets.SSH_USER }}

      - name: Setup SSH Key
        uses: benoitchantre/setup-ssh-authentication-action@1.0.0
        with:
          private-key: ${{ steps.sshprivatekey.outputs.value }}
          known-hosts: ${{ steps.sshhost.outputs.value }}

      - name: Deploy Laravel App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.sshhost.outputs.value }}
          username: ${{ steps.sshuser.outputs.value }}
          key: ${{ steps.sshprivatekey.outputs.value }}
          script: |
            cd /var/www/${{ steps.sshdirectory.outputs.value }}/
            git pull
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --optimize-autoloader --no-dev
            composer post-ci
